name: EMS WITH CICD with Gradle
run-name: Build by ${{ github.actor }} on ${{ github.ref_name }} - Run #${{ github.run_number }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Give permission
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew clean build -x test

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: ems_db
        ports:
          - 5432:5432
        volumes:
          - ${{ github.workspace }}/db/EMS_db.sql:/docker-entrypoint-initdb.d/EMS_db.sql
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Give permission
        run: chmod +x gradlew

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            echo "Waiting for Postgres..."
            sleep 2
          done
        env:
          PGPASSWORD: admin

      - name: Run Tests
        run: ./gradlew test
        env:
          DB_URL: jdbc:postgresql://localhost:5432/ems_db
          DB_USER: postgres
          DB_PASSWORD: admin
