name: Run Tests from Jira

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: "Jira issue key"
        required: false
        type: string

  repository_dispatch:
    types: [jira-test-trigger]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Print Jira issue
        run: echo "Triggered by ${{ github.event.inputs.issue_key }}"

      - name: Run Tests
        run: ./gradlew test
